### ISSUE TITLE
Support other means

### ISSUE THREAD

**Issue by VanessaFediuk** [jku-vds-lab/dashboard-onboarding#3]
Adding audio files and video files should be possible in the author view. We also need to show if a audio or video is attached to a node.

**Comment by VAISHALI-DHANOA** [comment]
https://blog.logrocket.com/how-to-create-video-audio-recorder-react/

**Comment by VAISHALI-DHANOA** [comment]
https://www.npmjs.com/package/react-video-recorder

**Comment by VAISHALI-DHANOA** [comment]
- [ ] Screen recording
- [ ] Video recording
- [ ] Audio recording
- [ ] Download recording
- [ ] Display recording in dashboard
